site_name: element.ai
site_description: e-textiles experiments documentation
site_author: Ieva Marija Dautartaitė
site_url: https://imdrift.github.io/element.ai/
theme:
  name: material
  logo: assets/5logo.png
  favicon: assets/favicon.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep orange
  
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - content.code.copy
  - content.code.select
  - content.code.annotate

extra:
  homepage: https://imdrift.github.io/element.ai/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/imdrift/element.ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ieva-marija-dautartaite/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aelementai/
 
markdown_extensions:
# Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - tags





nav:
  - Home: index.md
  - About: 
      - About me: about/about.md
      - Project: about/why.md
  - Experiments:
      - experiment №001: experiments/ex001.md


copyright: Copyright &copy; 2025 element.ai
  

