# Project information
site_name: element.ai
site_description: e-textiles experiments documentation
site_author: Ieva Marija Dautartaitė
site_url: https://imdrift.github.io/element.ai/

# Copyright
copyright: Copyright &copy; 2025 element.ai

# Repository
repo_name: imdrift/element.ai
repo_url: https://github.com/imdrift/element.ai

# Configuration
theme:
  name: material
  logo: assets/5logo.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: red
    
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: red
  
  features:
  - navigation.sections
  - navigation.tracking
  - toc.follow
  - navigation.top
  - navigation.footer
  - content.code.copy
  - content.code.select
  - content.code.annotate


# Extensions
extra:
  homepage: https://imdrift.github.io/element.ai/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/imdrift/element.ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ieva-marija-dautartaite/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aelementai/ 

markdown_extensions:

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption   
  - toc:
      permalink: true

plugins:
  - search
  - tags

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Welcome to the heaven of failures!: index.md
  - Experiments:
      - documentation: experiments/documentation.md
      - experiment №001: experiments/ex001.md
      - experiment №002: experiments/ex002.md
      - experiment №003: experiments/ex003.md
      - experiment №004: experiments/ex004.md
      - experiment №005: experiments/ex005.md



  

